[build]
  command = "npm run build && mkdir -p .next && cp -r dist/* .next/"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    nextConfigDir = "." 